version: '3.8'

services:
  happyrow-core:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database connection from environment variables
      - DATABASE_URL=${DATABASE_URL}
      # Override port if needed
      - PORT=${PORT:-8080}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - happyrow-network

networks:
  happyrow-network:
    driver: bridge
